{{- range $index, $stack := .Values.stacks}}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{$stack.name}}
  namespace: default
spec:
  generators:
  - git:
      repoURL: https://github.com/azaurus1/continuous-gitops-example-repo
      revision: HEAD
      directories:
      - path: stacks/{{$stack.name}}/*
  template:
    metadata:
      name: '{{`{{path.basename}}`}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/azaurus1/continuous-gitops-example-repo
        targetRevision: HEAD
        path: '{{`{{path}}`}}'
      destination:
        name: in-cluster
        namespace: {{$stack.namespace}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
{{- end }}
